module.exports = {
    preset: 'ts-jest',
    testEnvironment: 'node',
    roots: ['<rootDir>/src'],
    testMatch: ['**/__tests__/**/*.ts', '**/?(*.)+(spec|test).ts'],
    transform: {
        '^.+\\.ts$': 'ts-jest',
    },
    collectCoverageFrom: [
        'src/**/*.ts',
        '!src/**/*.d.ts',
        '!src/**/*.test.ts',
        '!src/**/*.spec.ts',
        '!src/**/index.ts',
    ],
    coverageDirectory: 'coverage',
    coverageReporters: ['text', 'lcov', 'html'],
    moduleNameMapper: {
        '^@shared/(.*)$': '<rootDir>/src/shared/$1',
        '^@services/(.*)$': '<rootDir>/src/services/$1',
        '^@config/(.*)$': '<rootDir>/src/shared/config/$1',
        '^@utils/(.*)$': '<rootDir>/src/shared/utils/$1',
        '^@middleware/(.*)$': '<rootDir>/src/shared/middleware/$1',
        '^@database/(.*)$': '<rootDir>/src/shared/database/$1',
        '^@auth/(.*)$': '<rootDir>/src/shared/auth/$1',
        '^@cache/(.*)$': '<rootDir>/src/shared/cache/$1',
        '^@messaging/(.*)$': '<rootDir>/src/shared/messaging/$1',
        '^@monitoring/(.*)$': '<rootDir>/src/shared/monitoring/$1',
        '^@cloud/(.*)$': '<rootDir>/src/shared/cloud/$1',
    },
    setupFilesAfterEnv: ['<rootDir>/tests/setup.ts'],
    testTimeout: 10000,
    verbose: true,
};
